#!/usr/bin/env python3
"""Check that the line sensors deliver FRESH data at ~30Hz.

Every sensor frame carries a frame_id generated by the firmware itself, so a
repeated frame_id means stale/repeated data and a frame_id jump means a dropped
frame. This tool polls the server's status ~100x/s and counts unique frame_ids.

Usage:  python3 check_line_sensor_hz.py [--duration 30] [--min-hz 29]
"""
import argparse
import sys
import time

from stretch4_body.subsystem.line_sensor import connect


# Settling bounds. A reader that has just opened the port runs behind the
# board and catches up in forward jumps; measuring across that reports skips
# that never happened. 
SETTLE_MAX_S = 20.0      # give up waiting and measure anyway
SETTLE_QUIET_S = 1.5     # this long with no jump == tracking the board
SETTLE_JUMP = 2          # frame_id advance per sample that counts as a jump


def sensor_names(conn):
    """The sensors this connection is actually reporting, in order."""
    return sorted(k for k in conn.loop.status if k.startswith('sensor_'))


def settle(conn, sensors, max_s=SETTLE_MAX_S):
    """Block until frame_id advances smoothly, or max_s passes.

    Returns (settled, seconds_waited).
    """
    t0 = time.time()
    last = {}
    calm_since = t0
    while True:
        conn.pull_status()
        now = time.time()
        for sn in sensors:
            f = (conn.loop.status.get(sn) or {}).get('frame_id', 0)
            prev = last.get(sn)
            if prev is not None and f > prev + SETTLE_JUMP:
                calm_since = now
            last[sn] = f
        if now - calm_since >= SETTLE_QUIET_S:
            return True, now - t0
        if now - t0 >= max_s:
            return False, now - t0
        time.sleep(0.003)


def measure(conn, sensors, duration_s):
    """Sample frame_id as fast as we can for duration_s. Returns (stats, span).

    Two rates come out of the same window, and they answer different questions:

      advance_hz  frame_id span / elapsed -- how fast the BOARD produces
                  frames, whether or not we managed to look at each one.
      fresh_hz    distinct frame_ids seen / elapsed -- how fast NEW data
                  actually reaches a reader. Below advance_hz when status is
                  published slower than the sensors run, or when we sample it
                  too slowly.

    Rates are per sensor because a single sensor can drop out of frames while
    the rest of the board keeps up.
    """
    samples = []
    t0 = time.time()
    while time.time() - t0 < duration_s:
        conn.pull_status()
        samples.append((time.time(),
                        {sn: (conn.loop.status.get(sn) or {}).get('frame_id', 0)
                         for sn in sensors}))
        time.sleep(0.003)

    span = (samples[-1][0] - samples[0][0]) if len(samples) > 1 else 0.0
    stats = {}
    for sn in sensors:
        fids = [row[1][sn] for row in samples]
        uniq = sorted(set(fids))
        gaps = [b - a for a, b in zip(uniq, uniq[1:])]
        # Both counts are "after the first sample", so they divide by the same
        # span: the frame sitting in status when we arrived is not new data.
        new_frames = len(uniq) - 1
        advance = fids[-1] - fids[0] if fids else 0
        stats[sn] = {
            'advance_hz': advance / span if span > 0 and advance > 0 else 0.0,
            'fresh_hz': new_frames / span if span > 0 and new_frames > 0 else 0.0,
            'new_frames': new_frames,
            'skips': sum(1 for g in gaps if g > 1),
            'max_gap': max(gaps) if gaps else 0,
            'backwards': sum(1 for a, b in zip(fids, fids[1:]) if b < a),
            'frame_id': fids[-1] if fids else 0,
        }
    return stats, span


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--duration', type=float, default=30.0,
                    help='measurement window in seconds (default 30)')
    ap.add_argument('--min-hz', type=float, default=29.0,
                    help='fresh-frame rate below this fails (default 29)')
    args = ap.parse_args()

    try:
        conn = connect.open_line_sensors('stretch_line_sensor_hz_check')
    except connect.LineSensorUnavailable as exc:
        sys.exit(f'FAIL: {exc.detail}')
    print(conn.describe())
    ls = conn.loop
    conn.pull_status()

    sensors = sensor_names(conn)
    if not sensors:
        conn.close()
        sys.exit("FAIL: no sensor_* entries in line_sensor_loop status")

    print("settling ...")
    settled, waited = settle(conn, sensors)
    if settled:
        print(f"  settled after {waited:.1f}s")
    else:
        print(f"  WARNING still jumping after {waited:.1f}s -- measuring anyway; "
              f"the reader is not keeping up with the board")

    print(f"measuring {len(sensors)} sensors for {args.duration:.0f}s ...")

    stats, span = measure(conn, sensors, args.duration)
    conn.close()

    ok = True
    print(f"\n{'sensor':<10} {'fresh Hz':>8} {'board Hz':>8} {'new frames':>10} "
          f"{'skips':>6} {'max gap':>7} {'backwards':>9}")
    for sn in sensors:
        m = stats[sn]
        flag = ''
        if m['fresh_hz'] < args.min_hz or m['backwards']:
            ok = False
            flag = '  <-- PROBLEM'
        print(f"{sn:<10} {m['fresh_hz']:8.2f} {m['advance_hz']:8.2f} "
              f"{m['new_frames']:10d} {m['skips']:6d} "
              f"{m['max_gap']:7d} {m['backwards']:9d}{flag}")

    h = ls.status.get('health') or {}
    print(f"\nserver-reported rate_hz: {ls.status.get('rate_hz', 0):.1f}   "
          f"decode_errors: {h.get('decode_errors')}")
    print("\nPASS: every sensor is streaming new (never repeated, never backwards) "
          "frames at >= %.0fHz" % args.min_hz if ok else
          "\nFAIL: at least one sensor is below rate or produced stale/backwards frames")
    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
