#!/usr/bin/env python3
"""Check that the line sensors deliver FRESH data at ~30Hz.

Every sensor frame carries a frame_id generated by the firmware itself, so a
repeated frame_id means stale/repeated data and a frame_id jump means a dropped
frame. This tool polls the server's status ~100x/s and counts unique frame_ids.

Usage:  python3 check_line_sensor_hz.py [--duration 30] [--min-hz 29]
"""
import argparse
import sys
import time

from stretch4_body.subsystem.line_sensor import connect


# Settling bounds. A reader that has just opened the port runs behind the
# board and catches up in forward jumps; measuring across that reports skips
# that never happened. 
SETTLE_MAX_S = 20.0      # give up waiting and measure anyway
SETTLE_QUIET_S = 1.5     # this long with no jump == tracking the board
SETTLE_JUMP = 2          # frame_id advance per sample that counts as a jump


def settle(conn, ls, sensors):
    """Block until frame_id advances smoothly, or SETTLE_MAX_S passes.

    Returns (settled, seconds_waited). Not cosmetic: until this returns, the
    ranges a tool reads are older than the floor in front of the robot.
    """
    t0 = time.time()
    last = {}
    calm_since = t0
    while True:
        conn.pull_status()
        now = time.time()
        for sn in sensors:
            f = (ls.status.get(sn) or {}).get('frame_id', 0)
            prev = last.get(sn)
            if prev is not None and f > prev + SETTLE_JUMP:
                calm_since = now
            last[sn] = f
        if now - calm_since >= SETTLE_QUIET_S:
            return True, now - t0
        if now - t0 >= SETTLE_MAX_S:
            return False, now - t0
        time.sleep(0.003)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('--duration', type=float, default=30.0,
                    help='measurement window in seconds (default 30)')
    ap.add_argument('--min-hz', type=float, default=29.0,
                    help='fresh-frame rate below this fails (default 29)')
    args = ap.parse_args()

    try:
        conn = connect.open_line_sensors('stretch_line_sensor_hz_check')
    except connect.LineSensorUnavailable as exc:
        sys.exit(f'FAIL: {exc.detail}')
    print(conn.describe())
    ls = conn.loop
    conn.pull_status()

    sensors = sorted(k for k in ls.status if k.startswith('sensor_'))
    if not sensors:
        conn.close()
        sys.exit("FAIL: no sensor_* entries in line_sensor_loop status")
   
    print("settling ...")
    settled, waited = settle(conn, ls, sensors)
    if settled:
        print(f"  settled after {waited:.1f}s")
    else:
        print(f"  WARNING still jumping after {waited:.1f}s -- measuring anyway; "
              f"the reader is not keeping up with the board")

    print(f"measuring {len(sensors)} sensors for {args.duration:.0f}s ...")

    samples = []
    t0 = time.time()
    while time.time() - t0 < args.duration:
        conn.pull_status()
        samples.append((time.time(),
                        {sn: (ls.status.get(sn) or {}).get('frame_id', 0)
                         for sn in sensors}))
        time.sleep(0.003)
    conn.close()

    span = samples[-1][0] - samples[0][0]
    ok = True
    print(f"\n{'sensor':<10} {'fresh Hz':>8} {'new frames':>10} {'skips':>6} "
          f"{'max gap':>7} {'backwards':>9}")
    for sn in sensors:
        fids = [r[1][sn] for r in samples]
        uniq = sorted(set(fids))
        gaps = [b - a for a, b in zip(uniq, uniq[1:])]
        skips = sum(1 for g in gaps if g > 1)
        max_gap = max(gaps) if gaps else 0
        backwards = sum(1 for a, b in zip(fids, fids[1:]) if b < a)
        hz = len(uniq) / span
        flag = ''
        if hz < args.min_hz or backwards:
            ok = False
            flag = '  <-- PROBLEM'
        print(f"{sn:<10} {hz:8.2f} {len(uniq):10d} {skips:6d} "
              f"{max_gap:7d} {backwards:9d}{flag}")

    h = ls.status.get('health') or {}
    print(f"\nserver-reported rate_hz: {ls.status.get('rate_hz', 0):.1f}   "
          f"decode_errors: {h.get('decode_errors')}   "
          f"fw_version: {h.get('fw_version') or '(no reply -- old firmware?)'}")
    print("\nPASS: every sensor is streaming new (never repeated, never backwards) "
          "frames at >= %.0fHz" % args.min_hz if ok else
          "\nFAIL: at least one sensor is below rate or produced stale/backwards frames")
    sys.exit(0 if ok else 1)


if __name__ == '__main__':
    main()
